version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-ra2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ra2-users
      MYSQL_USER: api_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
